-- BOOK_DATA : 책/저자 정보, MONTH_SALES : 2022년1월에 판매된 책ID와 갯수
WITH BOOK_DATA AS (
        SELECT B.BOOK_ID, A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, B.PRICE
        FROM BOOK B
        JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
    ),
    
    MONTH_SALES AS (
        SELECT BOOK_ID, SUM(SALES) AS SALES
        FROM BOOK_SALES
        WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
        GROUP BY BOOK_ID
        ORDER BY BOOK_ID
    )


SELECT BD.AUTHOR_ID, BD.AUTHOR_NAME, BD.CATEGORY, SUM(BD.PRICE * MS.SALES) AS TOTAL_SALES
FROM MONTH_SALES MS
LEFT OUTER JOIN BOOK_DATA BD ON MS.BOOK_ID = BD.BOOK_ID
GROUP BY BD.AUTHOR_ID, BD.CATEGORY
ORDER BY BD.AUTHOR_ID, BD.CATEGORY DESC

