-- 입양 간 동물중 보호기간이 가장 길었던 동물 두마리 아이디와 이름을 조회
SELECT AO.ANIMAL_ID, AO.NAME
FROM ANIMAL_OUTS AO
INNER JOIN ANIMAL_INS AI ON AO.ANIMAL_ID = AI.ANIMAL_ID
ORDER BY DATEDIFF(AI.DATETIME, AO.DATETIME) ASC
LIMIT 2;

