-- 중고거래 게시물을 3건 이상 등록한 사용자 조회
WITH SELECTED_USER AS (
    SELECT WRITER_ID, COUNT(BOARD_ID)
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(BOARD_ID) >= 3)
    
SELECT USER_ID, NICKNAME, CONCAT(CITY,' ', STREET_ADDRESS1, ' ',STREET_ADDRESS2) AS 전체주소, 
        CONCAT(SUBSTRING(TLNO,1,3),'-',SUBSTRING(TLNO,4,4),'-',SUBSTRING(TLNO,8,4)) AS 전화번호
FROM USED_GOODS_USER
HAVING USER_ID IN (SELECT WRITER_ID FROM SELECTED_USER)
ORDER BY USER_ID DESC;