-- 서울에 위치한 식당중
-- 리뷰 평균점수는 소수점 세번째에서 반올림
-- 결과는 평균점수를 기준으로 내림차순 정렬, 같다면 즐찾수 기준으로 내림차순
-- SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, ROUND(AVG(B.REVIEW_SCORE),3)
SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, ROUND(AVG(B.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO A INNER JOIN REST_REVIEW B 
ON A.REST_ID = B.REST_ID
WHERE A.ADDRESS LIKE '서울%'
GROUP BY B.REST_ID
ORDER BY SCORE DESC, A.FAVORITES DESC;