-- 생산일자가 2022년 5월인 식품들의 식품ID, 식품이름, 총매출을 조회
-- 결과는 총 매출을 기준으로 내림차순 정렬, 총매출이 같다면 식품ID를 기준으로 오름차순 정렬
WITH SUB_ORDER AS (
    SELECT *
    FROM FOOD_ORDER
    WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5)    
    
SELECT A.PRODUCT_ID AS PRODUCT_ID, B.PRODUCT_NAME, B.PRICE*SUM(A.AMOUNT) AS TOTAL_SALES
FROM SUB_ORDER A
INNER JOIN FOOD_PRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC



