-- 대여 시작일 기준으로 2022년 8월부터 2022년 10월까지 총 대여 횟수가 5회 이상인 자동차
-- 해당 기간동안의 월별 자동차 ID별 총 대여횟수 리스트를 출력

WITH UPPER_FIVE_CAR AS (
SELECT CAR_ID, COUNT(HISTORY_ID)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY CAR_ID
HAVING COUNT(HISTORY_ID) >= 5),

SELECTED_HISTORY AS (
SELECT HISTORY_ID, START_DATE, CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
      AND CAR_ID IN (SELECT CAR_ID FROM UPPER_FIVE_CAR)
)


SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM SELECTED_HISTORY
GROUP BY MONTH, CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH, CAR_ID DESC


