-- 물고기 종류별로 가장 큰 물고기 ID, 물고기 이름, 길이를 출력
-- 물고기 ID에 대해 오름차순 정렬
-- 물고기 타입으로 그룹바이하고 LENGTH가 가장 큰 녀석의 ID를 셀렉트한 뒤 이름과 조인하면 될듯

WITH MAX_FISH AS (SELECT A.ID, A.FISH_TYPE, B.MAX_LENGTH
FROM FISH_INFO A
INNER JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE) B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE A.LENGTH = B.MAX_LENGTH)

SELECT A.ID, B.FISH_NAME, A.MAX_LENGTH AS LENGTH
FROM MAX_FISH A
JOIN FISH_NAME_INFO B
ON A.FISH_TYPE = B.FISH_TYPE
ORDER BY A.ID