-- Having과 WHERE+in을 적극 활용합시다
SELECT B.ID, A.FISH_NAME, B.LENGTH
FROM FISH_NAME_INFO A
JOIN FISH_INFO B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE B.FISH_TYPE IN (
    SELECT FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING LENGTH = MAX(LENGTH)
    )
ORDER BY ID;